######################################################################
# Automatically generated by qmake (2.01a) dim. oct. 16 22:55:51 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Window.h
SOURCES += gui_main.cpp Window.cpp
