######################################################################
# Automatically generated by qmake (2.01a) dim. oct. 16 23:02:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lpthread

# Input
HEADERS += Window.h
SOURCES += capture_test.c gui_main.cpp Window.cpp
